# Generated by Django 4.2.5 on 2024-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='diesel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='gas92',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='gas95',
            field=models.FloatField(default=0.0),
        ),
    ]
