# Generated by Django 4.2.5 on 2024-02-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sale',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='tablet.sale'),
            preserve_default=False,
        ),
    ]
