# Generated by Django 4.2.5 on 2024-02-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0006_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.FloatField(default=12.5),
            preserve_default=False,
        ),
    ]
